//Mock data - Image links will not be accessible and new images will need to be sourced
module.exports.data =
	[
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "166 - Acorn",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_acorn.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "215 - Autumn Leaf",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_autumn1.webp","https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_autumn2.jpg","https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_autumn3.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_black1.webp","https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_black2.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "519 - Blue Ridge",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_blueRidge.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "307 - Dahlia",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_dahlia.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "527 - Deep Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_deepBlue.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "662 - Deep Forest",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_deepForest.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "660 - Forest Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_forestGreen1.webp", "https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_forestGreen2.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "664-904 - Frost Green-Chess Pattern",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_frostGreen.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "519 - Blue Ridge",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_blueRidge.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "031 - Graphite",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_graphite.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "620 - Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_green.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "326 - Ox Red",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_oxRed.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "420 - Plum",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_plum.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "325-915 - Deep Red-Random Blocked",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_redRandom.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "333 - Rowan Red",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_rowanRed.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "540 - Royal Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_royalBlue.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110.00,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": ["One Size"],
			"color": "046 - Super Grey",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_superGrey.webp"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_black1.webp"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "519 - Blue Ridge",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_blueRidge.webp"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "321 - Cabin Red",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_cabinRed.jpg"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "230 - Chestnut",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_chestnut.jpg"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "633 - Dark Olive",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_darkOlive1.webp", "https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_darkOlive2.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_darkOlive3.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_darkOlive4.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_darkOlive5.jpg"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "277 - Dark Sand",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_darkSand.webp"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "042 - Dusk",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_dusk.webp"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "560 - Navy",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_navy.webp"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "330 - Redwood",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_redwood.webp"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "638 - Storm",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_storm.jpg"]
		},
		{
			"name": "RAVEN 28",
			"type": "backpack",
			"description": "Donec feugiat metus sit. Nam consequat dolor vitae dolor. Sed eu eros. Donec fringilla.",
			"userRating": 4.7,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F26052",
			"size": ["One Size"],
			"color": "046 - Super Grey",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Raven+28/raven_superGrey.jpg"]
		},
		{
			"name": "YUPIK PARKA M",
			"type": "jacket",
			"description": "Feugiat metus sit donec. Consequat dolor namvitae dolor. Eros sed eu. Fringilla donec.",
			"userRating": 3.7,
			"totalRatings": 3,
			"price": 500.00,
			"gender": "Men's",
			"style": "Style # F80665",
			"size": ["XS - (Out of Stock)", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Yupik+Parka+M/yupik_black.jpg"]
		},
		{
			"name": "YUPIK PARKA M",
			"type": "jacket",
			"description": "Feugiat metus sit donec. Consequat dolor namvitae dolor. Eros sed eu. Fringilla donec.",
			"userRating": 3.7,
			"totalRatings": 3,
			"price": 500.00,
			"gender": "Men's",
			"style": "Style # F80665",
			"size": ["XS - (Out of Stock)", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "215 - Autumn Leaf",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Yupik+Parka+M/yupik_autumn.jpg"]
		},
		{
			"name": "YUPIK PARKA M",
			"type": "jacket",
			"description": "Feugiat metus sit donec. Consequat dolor namvitae dolor. Eros sed eu. Fringilla donec.",
			"userRating": 3.7,
			"totalRatings": 3,
			"price": 500.00,
			"gender": "Men's",
			"style": "Style # F80665",
			"size": ["XS - (Out of Stock)", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "555 - Dark Navy",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Yupik+Parka+M/yupik_darkNavy.jpg"]

		},
		{
			"name": "YUPIK PARKA M",
			"type": "jacket",
			"description": "Feugiat metus sit donec. Consequat dolor namvitae dolor. Eros sed eu. Fringilla donec.",
			"userRating": 3.7,
			"totalRatings": 3,
			"price": 500.00,
			"gender": "Men's",
			"style": "Style # F80665",
			"size": ["XS - (Out of Stock)", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "042 - Dusk",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Yupik+Parka+M/yupik_dusk.jpg"]
		},
		{
			"name": "YUPIK PARKA M",
			"type": "jacket",
			"description": "Feugiat metus sit donec. Consequat dolor namvitae dolor. Eros sed eu. Fringilla donec.",
			"userRating": 3.7,
			"totalRatings": 3,
			"price": 500.00,
			"gender": "Men's",
			"style": "Style # F80665",
			"size": ["XS - (Out of Stock)", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "032 - Mountain Grey",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Yupik+Parka+M/yupik_mountainGrey1.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Yupik+Parka+M/yupik_mountainGrey2.jpg"]
		},
		{
			"name": "STEN JACKET M",
			"type": "jacket",
			"description": "Metus sit donec feugiat. Dolor sequat namcon vitae rolod. Eu eros sed. Gilla donec frin.",
			"userRating": 4,
			"totalRatings": 7,
			"price": 200.00,
			"gender": "Men's",
			"style": "Style # F81679",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL - (Out of Stock)"],
			"color": "620 - Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Sten+Jacket+M/sten_green.jpg"]
		},
		{
			"name": "STEN JACKET M",
			"type": "jacket",
			"description": "Metus sit donec feugiat. Dolor sequat namcon vitae rolod. Eu eros sed. Gilla donec frin.",
			"userRating": 4,
			"totalRatings": 7,
			"price": 200.00,
			"gender": "Men's",
			"style": "Style # F81679",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL - (Out of Stock)"],
			"color": "042 - Dusk",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Sten+Jacket+M/sten_dusk.jpg"]

		},
		{
			"name": "STEN JACKET M",
			"type": "jacket",
			"description": "Metus sit donec feugiat. Dolor sequat namcon vitae rolod. Eu eros sed. Gilla donec frin.",
			"userRating": 4,
			"totalRatings": 7,
			"price": 200.00,
			"gender": "Men's",
			"style": "Style # F81679",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL - (Out of Stock)"],
			"color": "555 - Dark Navy",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Sten+Jacket+M/sten_darkNavy1.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Sten+Jacket+M/sten_darkNavy2.jpg"]
		},
		{
			"name": "STEN JACKET M",
			"type": "jacket",
			"description": "Metus sit donec feugiat. Dolor sequat namcon vitae rolod. Eu eros sed. Gilla donec frin.",
			"userRating": 4,
			"totalRatings": 7,
			"price": 200.00,
			"gender": "Men's",
			"style": "Style # F81679",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL - (Out of Stock)"],
			"color": "563 - Clay Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Sten+Jacket+M/sten_clayBlue1.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Sten+Jacket+M/sten_clayBlue2.jpg"]
		},
		{
			"name": "STEN JACKET M",
			"type": "jacket",
			"description": "Metus sit donec feugiat. Dolor sequat namcon vitae rolod. Eu eros sed. Gilla donec frin.",
			"userRating": 4,
			"totalRatings": 7,
			"price": 200.00,
			"gender": "Men's",
			"style": "Style # F81679",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL - (Out of Stock)"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Sten+Jacket+M/sten_black.jpg"]
		},
		{
			"name": "KAIPAK JACKET M",
			"type": "jacket",
			"description": "Sit donec feugiat monsefuat cetug. Camvitae dolor nolor. Dros cled peu. Pringotta Sodec.",
			"userRating": 5,
			"totalRatings": 17,
			"price": 225.00,
			"gender": "Men's",
			"style": "Style # F81166",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kaipak+Jacket+M/kaipak_black1.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Kaipak+Jacket+M/kaipak_black2.jpg"]
		},
		{
			"name": "KAIPAK JACKET M",
			"type": "jacket",
			"description": "Sit donec feugiat monsefuat cetug. Camvitae dolor nolor. Dros cled peu. Pringotta Sodec.",
			"userRating": 5,
			"totalRatings": 17,
			"price": 225.00,
			"gender": "Men's",
			"style": "Style # F81166",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "520-030 - Uncle Blue-Dark Grey",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kaipak+Jacket+M/kaipak_blueGrey1.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Kaipak+Jacket+M/kaipak_blueGrey2.jpg"]
		},
		{
			"name": "KAIPAK JACKET M",
			"type": "jacket",
			"description": "Sit donec feugiat monsefuat cetug. Camvitae dolor nolor. Dros cled peu. Pringotta Sodec.",
			"userRating": 5,
			"totalRatings": 17,
			"price": 225.00,
			"gender": "Men's",
			"style": "Style # F81166",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "633 - Dark Olive",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kaipak+Jacket+M/kaipak_darkOlive1.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Kaipak+Jacket+M/kaipak_darkOlive2.jpg"]
		},
		{
			"name": "KAIPAK JACKET M",
			"type": "jacket",
			"description": "Sit donec feugiat monsefuat cetug. Camvitae dolor nolor. Dros cled peu. Pringotta Sodec.",
			"userRating": 5,
			"totalRatings": 17,
			"price": 225.00,
			"gender": "Men's",
			"style": "Style # F81166",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "030-550 - Dark Grey-Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kaipak+Jacket+M/kaipak_greyBlack1.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Kaipak+Jacket+M/kaipak_greyBlack2.jpg"]
		},
		{
			"name": "KAIPAK JACKET M",
			"type": "jacket",
			"description": "Sit donec feugiat monsefuat cetug. Camvitae dolor nolor. Dros cled peu. Pringotta Sodec.",
			"userRating": 5,
			"totalRatings": 17,
			"price": 225.00,
			"gender": "Men's",
			"style": "Style # F81166",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "160-046 - Ochre-Super Grey",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kaipak+Jacket+M/kaipak_ochre1.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Kaipak+Jacket+M/kaipak_ochre2.jpg"]
		},
		{
			"name": "GREENLAND DOWN LINER JACKET M",
			"type": "jacket",
			"description": "Monsefuat camvitae. Dros dolor lit donec ottanolor. Feugiat cled peupring.",
			"userRating": 5,
			"totalRatings": 17,
			"price": 260.00,
			"gender": "Men's",
			"style": "Style # F87126",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "166 - Acorn",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Greenland+Down+Liner+Jacket+M/greenlandDown_acorn.jpg"]
		},
		{
			"name": "GREENLAND DOWN LINER JACKET M",
			"type": "jacket",
			"description": "Monsefuat camvitae. Dros dolor lit donec ottanolor. Feugiat cled peupring.",
			"userRating": 5,
			"totalRatings": 17,
			"price": 260.00,
			"gender": "Men's",
			"style": "Style # F87126",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Greenland+Down+Liner+Jacket+M/greenlandDown_black.jpg"]
		},
		{
			"name": "GREENLAND DOWN LINER JACKET M",
			"type": "jacket",
			"description": "Monsefuat camvitae. Dros dolor lit donec ottanolor. Feugiat cled peupring.",
			"userRating": 5,
			"totalRatings": 17,
			"price": 260.00,
			"gender": "Men's",
			"style": "Style # F87126",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "042 - Dusk",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Greenland+Down+Liner+Jacket+M/greenlandDown_dusk.jpg"]

		},
		{
			"name": "GREENLAND DOWN LINER JACKET M",
			"type": "jacket",
			"description": "Monsefuat camvitae. Dros dolor lit donec ottanolor. Feugiat cled peupring.",
			"userRating": 5,
			"totalRatings": 17,
			"price": 260.00,
			"gender": "Men's",
			"style": "Style # F87126",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "620 - Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Greenland+Down+Liner+Jacket+M/greenlandDown_green.jpg"]
		},
		{
			"name": "GREENLAND DOWN LINER JACKET M",
			"type": "jacket",
			"description": "Monsefuat camvitae. Dros dolor lit donec ottanolor. Feugiat cled peupring.",
			"userRating": 5,
			"totalRatings": 17,
			"price": 260.00,
			"gender": "Men's",
			"style": "Style # F87126",
			"size": ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
			"color": "575 - Night Sky",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Greenland+Down+Liner+Jacket+M/greenlandDown_nightSky.jpg"]
		},
		{
			"name": "KEB DOME",
			"type": "tent",
			"description": "Consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit",
			"userRating": 3,
			"totalRatings": 21,
			"price": 950.00,
			"gender": "Unisex",
			"style": "Style # F53702",
			"size": ["One Size"],
			"color": "525 - UN Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Keb+Dome/keb_blue.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Keb+Dome/keb_blue2.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Keb+Dome/keb_blue3.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Keb+Dome/keb_blue4.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Keb+Dome/keg_diag.jpg"]
		},
		{
			"name": "KEB DOME",
			"type": "tent",
			"description": "Consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit",
			"userRating": 3,
			"totalRatings": 21,
			"price": 950.00,
			"gender": "Unisex",
			"style": "Style # F53702",
			"size": ["One Size"],
			"color": "616 - Pine Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Keb+Dome/keb_green.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Keb+Dome/keg_diag.jpg"]
		},
		{
			"name": "ABISKO VIEW",
			"type": "tent",
			"description": "Aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui.",
			"userRating": 2,
			"totalRatings": 4,
			"price": 720.00,
			"gender": "Unisex",
			"style": "Style # F53402",
			"size": ["One Size"],
			"color": "616 - Pine Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+View+2/abiskoView_green.jpg"]
		},
		{
			"name": "ABISKO VIEW",
			"type": "tent",
			"description": "Aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui.",
			"userRating": 2,
			"totalRatings": 4,
			"price": 720.00,
			"gender": "Unisex",
			"style": "Style # F53402",
			"size": ["One Size"],
			"color": "525 - UN Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+View+2/abiskoView_blue.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+View+2/abiskoView_blue2.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+View+2/abiskoView_blue4.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+View+2/abiskoView_blue5.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+View+2/abiskoView_blue6.jpg"]
		},
		{
			"name": "ABISKO VIEW",
			"type": "tent",
			"description": "Aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui.",
			"userRating": 2,
			"totalRatings": 4,
			"price": 720.00,
			"gender": "Unisex",
			"style": "Style # F53402",
			"size": ["One Size"],
			"color": "220 - Sand",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+View+2/abiskoView_sand.jpg"]
		},
		{
			"name": "ABISKO LITE",
			"type": "tent",
			"description": "Volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque.",
			"userRating": 5,
			"totalRatings": 1,
			"price": 520.00,
			"gender": "Unisex",
			"style": "Style # F53301",
			"size": ["One Size"],
			"color": "220 - Sand",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_sand.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_sand2.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_sand3.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_sand4.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_sand5.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_sand_6.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_diag.jpg"]
		},
		{
			"name": "ABISKO LITE",
			"type": "tent",
			"description": "Volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque.",
			"userRating": 5,
			"totalRatings": 1,
			"price": 520.00,
			"gender": "Unisex",
			"style": "Style # F53301",
			"size": ["One Size"],
			"color": "525 - UN Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_blue.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_diag.jpg"]
		},
		{
			"name": "ABISKO LITE",
			"type": "tent",
			"description": "Volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque.",
			"userRating": 5,
			"totalRatings": 1,
			"price": 520.00,
			"gender": "Unisex",
			"style": "Style # F53301",
			"size": ["One Size"],
			"color": "616 - Pine Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_green.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite/abiskoLite_diag.jpg"]
		},
		{
			"name": "ABISKO LITE 3",
			"type": "tent",
			"description": "Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu",
			"userRating": 5,
			"totalRatings": 9,
			"price": 800.00,
			"gender": "Unisex",
			"style": "Style # F53303",
			"size": ["One Size"],
			"color": "616 - Pine Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite+3/abiskoLite3_green.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite+3/abiskoLite3_diag.jpg"]
		},
		{
			"name": "ABISKO LITE 3",
			"type": "tent",
			"description": "Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu",
			"userRating": 5,
			"totalRatings": 9,
			"price": 800.00,
			"gender": "Unisex",
			"style": "Style # F53303",
			"size": ["One Size"],
			"color": "525 - UN Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite+3/abiskoLite3_blue.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite+3/abiskoLite3_blue2.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite+3/abiskoLite3_diag.jpg"]
		},
		{
			"name": "ABISKO LITE 3",
			"type": "tent",
			"description": "Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu",
			"userRating": 5,
			"totalRatings": 9,
			"price": 800.00,
			"gender": "Unisex",
			"style": "Style # F53303",
			"size": ["One Size"],
			"color": "220 - Sand",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite+3/abiskoLite3_sand.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Lite+3/abiskoLite3_diag.jpg"]
		},
		{
			"name": "ABISKO DOME",
			"type": "tent",
			"description": "Aut augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum.",
			"userRating": 2.5,
			"totalRatings": 2,
			"price": 850.00,
			"gender": "Unisex",
			"style": "Style # F53502",
			"size": ["One Size"],
			"color": "220 - Sand",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Dome+2/abiskoDome3_sand.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Dome+2/abiskoDome3_diag.jpg"]
		},
		{
			"name": "ABISKO DOME",
			"type": "tent",
			"description": "Aut augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum.",
			"userRating": 2.5,
			"totalRatings": 2,
			"price": 850.00,
			"gender": "Unisex",
			"style": "Style # F53502",
			"size": ["One Size"],
			"color": "616 - Pine Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Dome+2/abiskoDome3_green.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Dome+2/abiskoDome3_diag.jpg"]
		},
		{
			"name": "ABISKO DOME",
			"type": "tent",
			"description": "Aut augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum.",
			"userRating": 2.5,
			"totalRatings": 2,
			"price": 850.00,
			"gender": "Unisex",
			"style": "Style # F53502",
			"size": ["One Size"],
			"color": "525 - UN Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Dome+2/abiskoDome3_blue.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Dome+2/abiskoDome3_blue2.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Dome+2/abiskoDome3_blue3.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/Abisko+Dome+2/abiskoDome3_diag.jpg"]
		},
		{
			"name": "STINA JACKET W",
			"type": "jacket",
			"description": "Natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero",
			"userRating": 5,
			"totalRatings": 6,
			"price": 200.00,
			"gender": "Women's",
			"style": "Style # F89234",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/stina+women's+jacket/stina_black.jpg"]
		},
		{
			"name": "STINA JACKET W",
			"type": "jacket",
			"description": "Natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero",
			"userRating": 5,
			"totalRatings": 6,
			"price": 200.00,
			"gender": "Women's",
			"style": "Style # F89234",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "555 - Dark Navy",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/stina+women's+jacket/stina_dark-navy.jpg"]

		},
		{
			"name": "STINA JACKET W",
			"type": "jacket",
			"description": "Natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero",
			"userRating": 5,
			"totalRatings": 6,
			"price": 200.00,
			"gender": "Women's",
			"style": "Style # F89234",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "620 - Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/stina+women's+jacket/stina_green.jpg"]
		},
		{
			"name": "STINA JACKET W",
			"type": "jacket",
			"description": "Natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero",
			"userRating": 5,
			"totalRatings": 6,
			"price": 200.00,
			"gender": "Women's",
			"style": "Style # F89234",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "420 - Plum",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/stina+women's+jacket/stina_plum.jpg"]
		},
		{
			"name": "STINA JACKET W",
			"type": "jacket",
			"description": "Natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero",
			"userRating": 5,
			"totalRatings": 6,
			"price": 200.00,
			"gender": "Women's",
			"style": "Style # F89234",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "342 - Raspberry Red",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/stina+women's+jacket/stina_raspberry.jpg"]
		},
		{
			"name": "STINA JACKET W",
			"type": "jacket",
			"description": "Natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero",
			"userRating": 5,
			"totalRatings": 6,
			"price": 200.00,
			"gender": "Women's",
			"style": "Style # F89234",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "516 - Sage Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/stina+women's+jacket/stina_sage-green.jpg"]
		},
		{
			"name": "KEB JACKET W",
			"type": "jacket",
			"description": "Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.",
			"userRating": 4,
			"totalRatings": 1,
			"price": 290.00,
			"gender": "Women's",
			"style": "Style # F89892",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "563-562 - Clay Blue-Mineral Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_bblue.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_bblue2.jpg"]
		},
		{
			"name": "KEB JACKET W",
			"type": "jacket",
			"description": "Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.",
			"userRating": 4,
			"totalRatings": 1,
			"price": 290.00,
			"gender": "Women's",
			"style": "Style # F89892",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_black.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_black2.jpg"]
		},
		{
			"name": "KEB JACKET W",
			"type": "jacket",
			"description": "Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.",
			"userRating": 4,
			"totalRatings": 1,
			"price": 290.00,
			"gender": "Women's",
			"style": "Style # F89892",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "356-420 - Dark Garnet-Plum",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_dark-plum.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_dark-plum2.jpg"]
		},
		{
			"name": "KEB JACKET W",
			"type": "jacket",
			"description": "Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.",
			"userRating": 4,
			"totalRatings": 1,
			"price": 290.00,
			"gender": "Women's",
			"style": "Style # F89892",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "555-520 - Dark Navy-Uncle Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_dark-uncle.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_dark-uncle2.jpg"]
		},
		{
			"name": "KEB JACKET W",
			"type": "jacket",
			"description": "Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.",
			"userRating": 4,
			"totalRatings": 1,
			"price": 290.00,
			"gender": "Women's",
			"style": "Style # F89892",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "662-625 - Deep Forest-Laurel Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_laurel-green.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_laurel-green2.jpg"]
		},
		{
			"name": "KEB JACKET W",
			"type": "jacket",
			"description": "Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.",
			"userRating": 4,
			"totalRatings": 1,
			"price": 290.00,
			"gender": "Women's",
			"style": "Style # F89892",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "326-335 - Ox Red-Lava",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_lava.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_lava2.jpg"]
		},
		{
			"name": "KEB JACKET W",
			"type": "jacket",
			"description": "Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.",
			"userRating": 4,
			"totalRatings": 1,
			"price": 290.00,
			"gender": "Women's",
			"style": "Style # F89892",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "525-018 UN Blue-Stone Grey",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_un-grey.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/keb+jacket+w/kebW_un-grey2.jpg"]
		},
		{
			"name": "SINGI DOWN JACKET W",
			"type": "jacket",
			"description": "Nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.",
			"userRating": 4.5,
			"totalRatings": 10,
			"price": 600.00,
			"gender": "Women's",
			"style": "Style # F89647",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/singi+down+jacket/singi_black.jpg"]
		},
		{
			"name": "SINGI DOWN JACKET W",
			"type": "jacket",
			"description": "Nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.",
			"userRating": 4.5,
			"totalRatings": 10,
			"price": 600.00,
			"gender": "Women's",
			"style": "Style # F89647",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "356 - Dark Garnet",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/singi+down+jacket/singi_dark-garnet.jpg"]

		},
		{
			"name": "SINGI DOWN JACKET W",
			"type": "jacket",
			"description": "Nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.",
			"userRating": 4.5,
			"totalRatings": 10,
			"price": 600.00,
			"gender": "Women's",
			"style": "Style # F89647",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "555 - Dark Navy",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/singi+down+jacket/singi_dark-navy.jpg"]
		},
		{
			"name": "SINGI DOWN JACKET W",
			"type": "jacket",
			"description": "Nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.",
			"userRating": 4.5,
			"totalRatings": 10,
			"price": 600.00,
			"gender": "Women's",
			"style": "Style # F89647",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "662 - Deep Forest",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/singi+down+jacket/singi_deep-forest.jpg"]
		},
		{
			"name": "SINGI DOWN JACKET W",
			"type": "jacket",
			"description": "Nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.",
			"userRating": 4.5,
			"totalRatings": 10,
			"price": 600.00,
			"gender": "Women's",
			"style": "Style # F89647",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "345 - Red Oak",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/singi+down+jacket/singi_red-oak.jpg"]
		},
		{
			"name": "NUUK PARKA W",
			"type": "jacket",
			"description": "Et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada.",
			"userRating": 4.5,
			"totalRatings": 9,
			"price": 500.00,
			"gender": "Women's",
			"style": "Style # F89655",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "555 - Dark Navy",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/nuuk+parka/nukk_dark-navy.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/nuuk+parka/nuuk_dark-navy2.jpg"]
		},
		{
			"name": "NUUK PARKA W",
			"type": "jacket",
			"description": "Et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada.",
			"userRating": 4.5,
			"totalRatings": 9,
			"price": 500.00,
			"gender": "Women's",
			"style": "Style # F89655",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "042 - Dusk",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/nuuk+parka/nuuk-dusk.jpg"]
		},
		{
			"name": "NUUK PARKA W",
			"type": "jacket",
			"description": "Et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada.",
			"userRating": 4.5,
			"totalRatings": 9,
			"price": 500.00,
			"gender": "Women's",
			"style": "Style # F89655",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/nuuk+parka/nuuk_black.jpg"]
		},
		{
			"name": "NUUK PARKA W",
			"type": "jacket",
			"description": "Et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada.",
			"userRating": 4.5,
			"totalRatings": 9,
			"price": 500.00,
			"gender": "Women's",
			"style": "Style # F89655",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "356 - Dark Garnet",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/nuuk+parka/nuuk_dark-garnet.jpg"]
		},
		{
			"name": "NUUK PARKA W",
			"type": "jacket",
			"description": "Et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada.",
			"userRating": 4.5,
			"totalRatings": 9,
			"price": 500.00,
			"gender": "Women's",
			"style": "Style # F89655",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "625 - Laurel Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/nuuk+parka/nuuk_laurel-green.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "166 - Acorn",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_acorn.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "215 - Autumn Leaf",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_autumn.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_black.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "519 - Blue Ridge",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_blue-ridge.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "307 - Dahlia",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_dahlia.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "356 - Dark Garnet",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_dark-garnet.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "662 - Deep Forest",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_deep-forest.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "042 - Dusk",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_dusk.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "664 - Frost Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_frost-green.jpg", "https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_frost-green2.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "646 - Glacier Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_glacier-green.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "620 - Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_green.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "560 - Navy",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_navy.jpg"]
		},
		{
			"name": "TOTEPACK NO.1",
			"type": "backpack",
			"description": "Arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat.",
			"userRating": 5,
			"totalRatings": 10,
			"price": 120.00,
			"gender": "Unisex",
			"style": "Style # F24203",
			"size": ["One Size"],
			"color": "046 - Super Grey",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/totepack/tote_super-grey.jpg"]
		},
		{
			"name": "SNOW FLAKE PARKA W",
			"type": "jacket",
			"description": "Integer tincidunt aliquam arcu. Nisi a odio semper cursus. Integer mollis. Nam interdum enim non nisi. Aliquam ultrices iaculis odio.",
			"userRating": 4.5,
			"totalRatings": 3,
			"price": 450.00,
			"gender": "Women's",
			"style": "Style # F80766",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "555 - Dark Navy",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/snowflake+parka/snowflake_dark-navy.jpg"]
		},
		{
			"name": "SNOW FLAKE PARKA W",
			"type": "jacket",
			"description": "Integer tincidunt aliquam arcu. Nisi a odio semper cursus. Integer mollis. Nam interdum enim non nisi. Aliquam ultrices iaculis odio.",
			"userRating": 4.5,
			"totalRatings": 3,
			"price": 450.00,
			"gender": "Women's",
			"style": "Style # F80766",
			"size": ["XXS", "XS", "S", "M", "L", "XL", "XXL"],
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/snowflake+parka/snowflake_black.jpg"]
		}
	]
