
module.exports.data =
	[
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "166 - Acorn",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_acorn.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "215 - Autumn Leaf",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_autumn1.webp","https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_autumn2.jpg","https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_autumn3.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "550 - Black",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_black1.webp","https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_black2.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "519 - Blue Ridge",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_blueRidge.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "307 - Dahlia",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_dahlia.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "527 - Deep Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_deepBlue.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "662 - Deep Forest",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_deepForest.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "660 - Forest Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_forestGreen1.webp", "https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_forestGreen2.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "664-904 - Frost Green-Chess Pattern",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_frostGreen.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "519 - Blue Ridge",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_blueRidge.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "031 - Graphite",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_graphite.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "620 - Green",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_green.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "326 - Ox Red",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_oxRed.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "420 - Plum",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_plum.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "325-915 - Deep Red-Random Blocked",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_redRandom.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "333 - Rowan Red",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_rowanRed.webp"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "540 - Royal Blue",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_royalBlue.jpg"]
		},
		{
			"name": "KANKEN LAPTOP 13\"",
			"type": "backpack",
			"description": "Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit",
			"userRating": 5,
			"totalRatings": 6,
			"price": 110,
			"gender": "Unisex",
			"style": "Style # F27171",
			"size": "One Size",
			"color": "046 - Super Grey",
			"url": ["https://hrphxfec.s3-us-west-1.amazonaws.com/Kanken+Laptop+13/kanken_superGrey.webp"]
		}
	];
